apiVersion: v1
kind: Service
metadata:
  name: deploy-watson-vr-service
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 5000
    name: http
    nodePort: 30000
  selector:
    app: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-watson-vr-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: deploy-watson-vr
        image: us.icr.io/<namespace>/watson-vr-flask:v1
        ports:
        - containerPort: 5000
#        imagePullPolicy: Always
        volumeMounts:
            - mountPath: /opt/vr-service-bind
              name: service-bind-volume
      volumes:
        - name: service-bind-volume
          secret:
            defaultMode: 420
            secretName: <secretName-binding-visual_recognition>